#!/usr/bin/env sh

ln -s $PWD/.ackrc ~
ln -s $PWD/.bashrc ~
ln -s $PWD/.gitconfig ~
ln -s $PWD/.vimrc ~
ln -s $PWD/.gitignore_global ~

curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/git-completion.bash
